[project]
name = "rapids-singlecell-reproducibility"
version = "0.0.0"
requires-python = ">=3.12,<3.15"
dependencies = [
    "bbknn",
    "decoupler>=2",
    "fa2-modified",
    "igraph",
    "leidenalg",
    "louvain",
    "pertpy",
    "pooch",
    "rapids-singlecell[rapids-cu12]; sys_platform == 'linux'",
    "scanpy>=1.11,<2",
    "squidpy>=1.8,<2",
]

[tool.uv]
package = false

[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 120

[tool.ruff.lint]
select = [
    "F",  # Errors detected by Pyflakes
    "E",  # Error detected by Pycodestyle
    "W",  # Warning detected by Pycodestyle
    "I",  # isort
    #"D",  # pydocstyle
    "B",  # flake8-bugbear
    "TID",  # flake8-tidy-imports
    "C4",  # flake8-comprehensions
    "BLE",  # flake8-blind-except
    "UP",  # pyupgrade
    "RUF100",  # Report unused noqa directives
    "TCH",  # Typing imports
    "NPY",  # Numpy specific rules
    "PTH"  # Use pathlib
]
ignore = [
    "E501",
    "E731",
    "E741",
    "D104",
    "D100",
    "D107",
    "B008",
    "D105",
    "D400",
    "D401",
    "D203",
    "D213",
    "F401",
    "N813",
    "E402",
    "F821",
    "PTH123"
]
